# SPDX-License-Identifier: GPL-2.0
snd-rust-dummy-y		:= dummy.o
snd-rust-ens1370-y		:= ens1370.o
snd-rust-intel8x0-y		:= intel8x0.o

obj-$(CONFIG_SND_RUST_DUMMY)	+= snd-rust-dummy.o
obj-$(CONFIG_SND_RUST_ENS1370)	+= snd-rust-ens1370.o
obj-$(CONFIG_SND_RUST_INTEL8X0)	+= snd-rust-intel8x0.o
